export type CountryCallingCode = {
  iso: string;
  name: string;
  dialCode: string;
  flag: string;
  aliases?: string[];
};

type CountryEntry = Omit<CountryCallingCode, "flag">;

function countryFlag(iso: string) {
  return iso
    .toUpperCase()
    .split("")
    .map((character) => String.fromCodePoint(127397 + character.charCodeAt(0)))
    .join("");
}

const entries: CountryEntry[] = [
  { iso: "US", name: "United States", dialCode: "+1", aliases: ["USA", "America", "美国"] },
  { iso: "CA", name: "Canada", dialCode: "+1", aliases: ["加拿大"] },
  { iso: "CN", name: "China", dialCode: "+86", aliases: ["PRC", "中国"] },
  { iso: "HK", name: "Hong Kong", dialCode: "+852", aliases: ["香港"] },
  { iso: "MO", name: "Macao", dialCode: "+853", aliases: ["Macau", "澳门"] },
  { iso: "TW", name: "Taiwan", dialCode: "+886", aliases: ["台湾"] },
  { iso: "GB", name: "United Kingdom", dialCode: "+44", aliases: ["UK", "Britain", "英国"] },
  { iso: "AU", name: "Australia", dialCode: "+61", aliases: ["澳大利亚"] },
  { iso: "NZ", name: "New Zealand", dialCode: "+64", aliases: ["新西兰"] },
  { iso: "JP", name: "Japan", dialCode: "+81", aliases: ["日本"] },
  { iso: "KR", name: "South Korea", dialCode: "+82", aliases: ["Korea", "韩国"] },
  { iso: "SG", name: "Singapore", dialCode: "+65", aliases: ["新加坡"] },
  { iso: "MY", name: "Malaysia", dialCode: "+60", aliases: ["马来西亚"] },
  { iso: "TH", name: "Thailand", dialCode: "+66", aliases: ["泰国"] },
  { iso: "VN", name: "Vietnam", dialCode: "+84", aliases: ["越南"] },
  { iso: "PH", name: "Philippines", dialCode: "+63", aliases: ["菲律宾"] },
  { iso: "ID", name: "Indonesia", dialCode: "+62", aliases: ["印度尼西亚"] },
  { iso: "IN", name: "India", dialCode: "+91", aliases: ["印度"] },
  { iso: "PK", name: "Pakistan", dialCode: "+92" },
  { iso: "BD", name: "Bangladesh", dialCode: "+880" },
  { iso: "LK", name: "Sri Lanka", dialCode: "+94" },
  { iso: "NP", name: "Nepal", dialCode: "+977" },
  { iso: "BT", name: "Bhutan", dialCode: "+975" },
  { iso: "MV", name: "Maldives", dialCode: "+960" },
  { iso: "MN", name: "Mongolia", dialCode: "+976" },
  { iso: "MM", name: "Myanmar", dialCode: "+95" },
  { iso: "KH", name: "Cambodia", dialCode: "+855" },
  { iso: "LA", name: "Laos", dialCode: "+856" },
  { iso: "BN", name: "Brunei", dialCode: "+673" },
  { iso: "TL", name: "Timor-Leste", dialCode: "+670" },
  { iso: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { iso: "UZ", name: "Uzbekistan", dialCode: "+998" },
  { iso: "KG", name: "Kyrgyzstan", dialCode: "+996" },
  { iso: "TJ", name: "Tajikistan", dialCode: "+992" },
  { iso: "TM", name: "Turkmenistan", dialCode: "+993" },
  { iso: "AF", name: "Afghanistan", dialCode: "+93" },
  { iso: "DE", name: "Germany", dialCode: "+49", aliases: ["Deutschland", "德国"] },
  { iso: "FR", name: "France", dialCode: "+33", aliases: ["法国"] },
  { iso: "IT", name: "Italy", dialCode: "+39", aliases: ["Italia", "意大利"] },
  { iso: "ES", name: "Spain", dialCode: "+34", aliases: ["España", "西班牙"] },
  { iso: "PT", name: "Portugal", dialCode: "+351" },
  { iso: "NL", name: "Netherlands", dialCode: "+31", aliases: ["Holland", "荷兰"] },
  { iso: "BE", name: "Belgium", dialCode: "+32" },
  { iso: "LU", name: "Luxembourg", dialCode: "+352" },
  { iso: "IE", name: "Ireland", dialCode: "+353" },
  { iso: "IS", name: "Iceland", dialCode: "+354" },
  { iso: "DK", name: "Denmark", dialCode: "+45" },
  { iso: "NO", name: "Norway", dialCode: "+47" },
  { iso: "SE", name: "Sweden", dialCode: "+46" },
  { iso: "FI", name: "Finland", dialCode: "+358" },
  { iso: "CH", name: "Switzerland", dialCode: "+41" },
  { iso: "AT", name: "Austria", dialCode: "+43" },
  { iso: "PL", name: "Poland", dialCode: "+48" },
  { iso: "CZ", name: "Czechia", dialCode: "+420", aliases: ["Czech Republic"] },
  { iso: "SK", name: "Slovakia", dialCode: "+421" },
  { iso: "HU", name: "Hungary", dialCode: "+36" },
  { iso: "RO", name: "Romania", dialCode: "+40" },
  { iso: "BG", name: "Bulgaria", dialCode: "+359" },
  { iso: "GR", name: "Greece", dialCode: "+30" },
  { iso: "AL", name: "Albania", dialCode: "+355" },
  { iso: "AD", name: "Andorra", dialCode: "+376" },
  { iso: "BA", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { iso: "HR", name: "Croatia", dialCode: "+385" },
  { iso: "CY", name: "Cyprus", dialCode: "+357" },
  { iso: "EE", name: "Estonia", dialCode: "+372" },
  { iso: "LV", name: "Latvia", dialCode: "+371" },
  { iso: "LT", name: "Lithuania", dialCode: "+370" },
  { iso: "MT", name: "Malta", dialCode: "+356" },
  { iso: "MD", name: "Moldova", dialCode: "+373" },
  { iso: "MC", name: "Monaco", dialCode: "+377" },
  { iso: "ME", name: "Montenegro", dialCode: "+382" },
  { iso: "MK", name: "North Macedonia", dialCode: "+389" },
  { iso: "RS", name: "Serbia", dialCode: "+381" },
  { iso: "SI", name: "Slovenia", dialCode: "+386" },
  { iso: "UA", name: "Ukraine", dialCode: "+380" },
  { iso: "BY", name: "Belarus", dialCode: "+375" },
  { iso: "RU", name: "Russia", dialCode: "+7" },
  { iso: "GE", name: "Georgia", dialCode: "+995" },
  { iso: "AM", name: "Armenia", dialCode: "+374" },
  { iso: "AZ", name: "Azerbaijan", dialCode: "+994" },
  { iso: "TR", name: "Türkiye", dialCode: "+90", aliases: ["Turkey"] },
  { iso: "IL", name: "Israel", dialCode: "+972" },
  { iso: "PS", name: "Palestine", dialCode: "+970" },
  { iso: "JO", name: "Jordan", dialCode: "+962" },
  { iso: "LB", name: "Lebanon", dialCode: "+961" },
  { iso: "SY", name: "Syria", dialCode: "+963" },
  { iso: "IQ", name: "Iraq", dialCode: "+964" },
  { iso: "IR", name: "Iran", dialCode: "+98" },
  { iso: "SA", name: "Saudi Arabia", dialCode: "+966" },
  { iso: "AE", name: "United Arab Emirates", dialCode: "+971", aliases: ["UAE"] },
  { iso: "QA", name: "Qatar", dialCode: "+974" },
  { iso: "KW", name: "Kuwait", dialCode: "+965" },
  { iso: "BH", name: "Bahrain", dialCode: "+973" },
  { iso: "OM", name: "Oman", dialCode: "+968" },
  { iso: "YE", name: "Yemen", dialCode: "+967" },
  { iso: "MX", name: "Mexico", dialCode: "+52", aliases: ["México", "墨西哥"] },
  { iso: "GT", name: "Guatemala", dialCode: "+502" },
  { iso: "BZ", name: "Belize", dialCode: "+501" },
  { iso: "SV", name: "El Salvador", dialCode: "+503" },
  { iso: "HN", name: "Honduras", dialCode: "+504" },
  { iso: "NI", name: "Nicaragua", dialCode: "+505" },
  { iso: "CR", name: "Costa Rica", dialCode: "+506" },
  { iso: "PA", name: "Panama", dialCode: "+507" },
  { iso: "CU", name: "Cuba", dialCode: "+53" },
  { iso: "JM", name: "Jamaica", dialCode: "+1" },
  { iso: "HT", name: "Haiti", dialCode: "+509" },
  { iso: "DO", name: "Dominican Republic", dialCode: "+1" },
  { iso: "BS", name: "Bahamas", dialCode: "+1" },
  { iso: "BB", name: "Barbados", dialCode: "+1" },
  { iso: "TT", name: "Trinidad and Tobago", dialCode: "+1" },
  { iso: "AG", name: "Antigua and Barbuda", dialCode: "+1" },
  { iso: "DM", name: "Dominica", dialCode: "+1" },
  { iso: "GD", name: "Grenada", dialCode: "+1" },
  { iso: "KN", name: "Saint Kitts and Nevis", dialCode: "+1" },
  { iso: "LC", name: "Saint Lucia", dialCode: "+1" },
  { iso: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1" },
  { iso: "BR", name: "Brazil", dialCode: "+55", aliases: ["Brasil", "巴西"] },
  { iso: "AR", name: "Argentina", dialCode: "+54" },
  { iso: "CL", name: "Chile", dialCode: "+56" },
  { iso: "CO", name: "Colombia", dialCode: "+57" },
  { iso: "PE", name: "Peru", dialCode: "+51" },
  { iso: "VE", name: "Venezuela", dialCode: "+58" },
  { iso: "EC", name: "Ecuador", dialCode: "+593" },
  { iso: "BO", name: "Bolivia", dialCode: "+591" },
  { iso: "PY", name: "Paraguay", dialCode: "+595" },
  { iso: "UY", name: "Uruguay", dialCode: "+598" },
  { iso: "GY", name: "Guyana", dialCode: "+592" },
  { iso: "SR", name: "Suriname", dialCode: "+597" },
  { iso: "ZA", name: "South Africa", dialCode: "+27" },
  { iso: "EG", name: "Egypt", dialCode: "+20" },
  { iso: "MA", name: "Morocco", dialCode: "+212" },
  { iso: "DZ", name: "Algeria", dialCode: "+213" },
  { iso: "TN", name: "Tunisia", dialCode: "+216" },
  { iso: "LY", name: "Libya", dialCode: "+218" },
  { iso: "SD", name: "Sudan", dialCode: "+249" },
  { iso: "SS", name: "South Sudan", dialCode: "+211" },
  { iso: "ET", name: "Ethiopia", dialCode: "+251" },
  { iso: "ER", name: "Eritrea", dialCode: "+291" },
  { iso: "DJ", name: "Djibouti", dialCode: "+253" },
  { iso: "SO", name: "Somalia", dialCode: "+252" },
  { iso: "KE", name: "Kenya", dialCode: "+254" },
  { iso: "UG", name: "Uganda", dialCode: "+256" },
  { iso: "TZ", name: "Tanzania", dialCode: "+255" },
  { iso: "RW", name: "Rwanda", dialCode: "+250" },
  { iso: "BI", name: "Burundi", dialCode: "+257" },
  { iso: "CD", name: "DR Congo", dialCode: "+243" },
  { iso: "CG", name: "Congo", dialCode: "+242" },
  { iso: "GA", name: "Gabon", dialCode: "+241" },
  { iso: "GQ", name: "Equatorial Guinea", dialCode: "+240" },
  { iso: "CM", name: "Cameroon", dialCode: "+237" },
  { iso: "CF", name: "Central African Republic", dialCode: "+236" },
  { iso: "TD", name: "Chad", dialCode: "+235" },
  { iso: "NG", name: "Nigeria", dialCode: "+234" },
  { iso: "NE", name: "Niger", dialCode: "+227" },
  { iso: "GH", name: "Ghana", dialCode: "+233" },
  { iso: "CI", name: "Côte d'Ivoire", dialCode: "+225", aliases: ["Ivory Coast"] },
  { iso: "SN", name: "Senegal", dialCode: "+221" },
  { iso: "ML", name: "Mali", dialCode: "+223" },
  { iso: "BF", name: "Burkina Faso", dialCode: "+226" },
  { iso: "BJ", name: "Benin", dialCode: "+229" },
  { iso: "TG", name: "Togo", dialCode: "+228" },
  { iso: "LR", name: "Liberia", dialCode: "+231" },
  { iso: "SL", name: "Sierra Leone", dialCode: "+232" },
  { iso: "GN", name: "Guinea", dialCode: "+224" },
  { iso: "GW", name: "Guinea-Bissau", dialCode: "+245" },
  { iso: "GM", name: "Gambia", dialCode: "+220" },
  { iso: "MR", name: "Mauritania", dialCode: "+222" },
  { iso: "CV", name: "Cabo Verde", dialCode: "+238" },
  { iso: "AO", name: "Angola", dialCode: "+244" },
  { iso: "ZM", name: "Zambia", dialCode: "+260" },
  { iso: "ZW", name: "Zimbabwe", dialCode: "+263" },
  { iso: "BW", name: "Botswana", dialCode: "+267" },
  { iso: "NA", name: "Namibia", dialCode: "+264" },
  { iso: "MZ", name: "Mozambique", dialCode: "+258" },
  { iso: "MW", name: "Malawi", dialCode: "+265" },
  { iso: "LS", name: "Lesotho", dialCode: "+266" },
  { iso: "SZ", name: "Eswatini", dialCode: "+268" },
  { iso: "MG", name: "Madagascar", dialCode: "+261" },
  { iso: "MU", name: "Mauritius", dialCode: "+230" },
  { iso: "SC", name: "Seychelles", dialCode: "+248" },
  { iso: "KM", name: "Comoros", dialCode: "+269" },
  { iso: "FJ", name: "Fiji", dialCode: "+679" },
  { iso: "PG", name: "Papua New Guinea", dialCode: "+675" },
  { iso: "SB", name: "Solomon Islands", dialCode: "+677" },
  { iso: "VU", name: "Vanuatu", dialCode: "+678" },
  { iso: "WS", name: "Samoa", dialCode: "+685" },
  { iso: "TO", name: "Tonga", dialCode: "+676" },
  { iso: "KI", name: "Kiribati", dialCode: "+686" },
  { iso: "TV", name: "Tuvalu", dialCode: "+688" },
  { iso: "NR", name: "Nauru", dialCode: "+674" },
  { iso: "PW", name: "Palau", dialCode: "+680" },
  { iso: "FM", name: "Micronesia", dialCode: "+691" },
  { iso: "MH", name: "Marshall Islands", dialCode: "+692" }
];

export const countryCallingCodes: CountryCallingCode[] = entries.map((entry) => ({
  ...entry,
  flag: countryFlag(entry.iso)
}));

export function callingCodeForCountry(countryCode?: string | null) {
  const normalized = countryCode?.trim().toUpperCase();
  return countryCallingCodes.find((country) => country.iso === normalized) || countryCallingCodes[0];
}
